# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# add_calculate_field.py
# Created on: 2021-12-20 11:27:57.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
clipped_lewisville_parcels = "clipped_lewisville_parcels"
clipped_lewisville_parcels__4_ = clipped_lewisville_parcels
clipped_lewisville_parcels__2_ = clipped_lewisville_parcels__4_

# Process: Add Field
arcpy.AddField_management(clipped_lewisville_parcels, "Plats", "TEXT", "", "", "200", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(clipped_lewisville_parcels__4_, "Plats", "\"https://www.dentoncad.net/data/_uploaded/plats/\" + ABST_SUBD_NUM + \".tif\"", "PYTHON_9.3", "")

