# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# gis03_hosted.py
# Created on: 2021-12-14 16:54:51.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
TrackStarLatestPositions3_mxd = "F:\\arcgisserver\\TrackStarLatestPositions3.mxd"
Web_map_URL = ""

arcpy.MXDToWebMap_server(TrackStarLatestPositions3_mxd, "TrackStarLatestPositions3", "TrackStarLatestPositions3", "TrackStarLatestPositions3", "", "Streets", "gis03_hosted", "MY_ORGANIZATION", "MY_GROUPS", "", "", "")
# Process: MXD to Web map


var _parcelsQueryURL = 'https://webadapt1.cityoflewisville.com/arcgis/rest/services/DevelopmentServices/Parcels_Pro_1071/MapServer/0'

var waterLines = 'https://services2.arcgis.com/kXGqZY4GIOcEYxoF/ArcGIS/rest/services/Water_System/FeatureServer/5'
var waterLinePoints = 'https://services2.arcgis.com/kXGqZY4GIOcEYxoF/ArcGIS/rest/services/Water_System/FeatureServer/3'
var fireHydrats = 'https://services2.arcgis.com/kXGqZY4GIOcEYxoF/ArcGIS/rest/services/Water_System/FeatureServer/1'

var sewerLinePoints = 'https://webadapt1.cityoflewisville.com/arcgis/rest/services/PublicServices/SanitarySewer__Pro_1071/MapServer/0'
var sewerLines = 'https://webadapt1.cityoflewisville.com/arcgis/rest/services/PublicServices/SanitarySewer__Pro_1071/MapServer/1'

var stormLinePoints = 'https://webadapt1.cityoflewisville.com/arcgis/rest/services/PublicServices/StormSystem_Pro_1071/MapServer/1'
var stormLines = 'https://webadapt1.cityoflewisville.com/arcgis/rest/services/PublicServices/StormSystem_Pro_1071/MapServer/2'